// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LCH.Abp.WebhooksManagement;
using LCH.Abp.WebhooksManagement.Integration;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LCH.Abp.WebhooksManagement.Integration;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWebhookPublishIntegrationService), typeof(WebhookPublishIntegrationClientProxy))]
[IntegrationService]
public partial class WebhookPublishIntegrationClientProxy : ClientProxyBase<IWebhookPublishIntegrationService>, IWebhookPublishIntegrationService
{
    public virtual async Task PublishAsync(WebhookPublishInput input)
    {
        await RequestAsync(nameof(PublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WebhookPublishInput), input }
        });
    }
}
